// NPCAnimationController.cs
//
// PYQUEST NPC GUIDE ANIMATION — idle + talk only.
//
// NPC guides never walk, so this controller drives exactly two states:
//   Idle — default, loops forever
//   Talk — gesturing loop while the NPC's dialogue sequence is playing
//
// WHERE IT LIVES (matches your hierarchy):
//   NPC Guide (empty root)
//     ?? InteractTrigger  ? NPCController + THIS script go here
//          ?? NPCModel    ? the Animator lives on this child (auto-found)
//
// HOW IT'S DRIVEN (same pattern as EncounterManager -> enemy Animator):
//   NPCController calls PlayTalk() when its dialogue sequence starts and
//   BackToIdle() when it ends (see the three one-line hooks marked
//   "NPC ANIMATION HOOK" in NPCController). The Animator Controller itself
//   is generated by NPCAnimatorBuilder (Tools > PyQuest menu), which wires
//   the "Talk" and "Idle" triggers this script fires.

using UnityEngine;

[DisallowMultipleComponent]
public class NPCAnimationController : MonoBehaviour
{
    [Header("Model (optional — auto-found if left empty)")]
    [Tooltip("The NPC's model child. Leave empty to use NPCController.npcModel, then fall back to an Animator anywhere under this object.")]
    public GameObject npcModel;

    [Header("Animator (optional — auto-found if left empty)")]
    [Tooltip("The Animator on the NPC model. Leave empty and it will be located automatically.")]
    public Animator animator;

    [Header("Behavior")]
    [Tooltip("Cross-fade seconds when switching between Idle and Talk.")]
    public float transitionDuration = 0.2f;
    [Tooltip("If true, the NPC keeps the Talk gesture while the player stands in range even outside dialogue. Leave off for plain idle-in-range behavior.")]
    public bool talkWhilePlayerNearby = false;

    // Trigger names — must match NPCAnimatorBuilder EXACTLY.
    public const string TriggerTalk = "Talk";
    public const string TriggerIdle = "Idle";

    public bool IsTalking { get; private set; }

    Animator ResolveAnimator()
    {
        if (animator != null) return animator;

        // 1. Explicit model reference wins.
        if (npcModel != null)
        {
            animator = npcModel.GetComponentInChildren<Animator>(true);
            if (animator != null) return animator;
        }

        // 2. Fall back to the sibling NPCController's npcModel reference
        //    (both scripts live on the InteractTrigger object).
        NPCController npc = GetComponent<NPCController>();
        if (npc == null) npc = GetComponentInParent<NPCController>();
        if (npc != null && npc.npcModel != null)
        {
            animator = npc.npcModel.GetComponentInChildren<Animator>(true);
            if (animator != null) return animator;
        }

        // 3. Last resort: any Animator under this object (the InteractTrigger),
        //    which is the model's parent, so this covers the model child too.
        animator = GetComponentInChildren<Animator>(true);
        return animator;
    }

    void Start()
    {
        ResolveAnimator();

        if (animator == null)
            Debug.LogWarning($"[NPCAnimationController] No Animator found for '{name}'. Talk/Idle triggers will be ignored. Assign the Animator or npcModel in the Inspector.");
        else if (animator.runtimeAnimatorController == null)
            Debug.LogWarning($"[NPCAnimationController] Animator '{animator.name}' has no controller assigned. Run Tools > PyQuest > Create NPC Guide Animator Controller.");
    }

    /// <summary>Switch the NPC into its Talk loop (called by NPCController when dialogue starts).</summary>
    public void PlayTalk()
    {
        if (animator == null) ResolveAnimator();
        if (animator == null || IsTalking) return;

        IsTalking = true;
        animator.ResetTrigger(TriggerIdle);
        animator.SetTrigger(TriggerTalk);
    }

    /// <summary>Return the NPC to its Idle loop (called when dialogue ends or the NPC departs).</summary>
    public void BackToIdle()
    {
        if (animator == null) ResolveAnimator();
        if (animator == null || !IsTalking) return;

        IsTalking = false;
        animator.ResetTrigger(TriggerTalk);
        animator.SetTrigger(TriggerIdle);
    }

    /// <summary>Convenience for optional custom calls: force a hard stop of both triggers.</summary>
    public void ResetToIdle()
    {
        IsTalking = false;
        if (animator == null) return;
        animator.ResetTrigger(TriggerTalk);
        animator.ResetTrigger(TriggerIdle);
        animator.CrossFade("Idle", transitionDuration);
    }

    // Optional fallback mode: talk whenever the player is simply in range,
    // even without dialogue. Off by default; the normal path is trigger-based.
    bool playerNearbyCached;

    void Update()
    {
        if (!talkWhilePlayerNearby) return;

        NPCController npc = GetComponent<NPCController>();
        if (npc == null) return;

        bool inRange = npc.IsPlayerInRange() && !npc.HasDeparted();
        if (inRange == playerNearbyCached) return;

        playerNearbyCached = inRange;
        if (inRange) PlayTalk();
        else BackToIdle();
    }

    void OnDisable()
    {
        // If the guide is deactivated (e.g. after Depart's SetActive(false)),
        // clear the talking flag so a reactivated NPC starts from Idle.
        IsTalking = false;
    }
}
